package org.matsim.episim.run.modules;

import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import jakarta.inject.Singleton;
import org.matsim.api.core.v01.Scenario;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.config.groups.VspExperimentalConfigGroup;
import org.matsim.core.controler.ControllerUtils;
import org.matsim.core.scenario.ScenarioUtils;
import org.matsim.episim.EpisimConfigGroup;
import org.matsim.episim.PathogenConfigGroup;
import org.matsim.episim.TracingConfigGroup;
import org.matsim.episim.VirusStrainConfigGroup;
import org.matsim.episim.model.AgeAndProgressionDependentInfectionModelWithSeasonality;
import org.matsim.episim.model.AntibodyModel;
import org.matsim.episim.model.ContactModel;
import org.matsim.episim.model.InfectionModel;
import org.matsim.episim.model.SymmetricContactModel;
import org.matsim.episim.model.activity.ActivityParticipationModel;
import org.matsim.episim.model.activity.DefaultParticipationModel;
import org.matsim.episim.model.progression.AgeDependentDiseaseStatusTransitionModel;
import org.matsim.episim.model.progression.DiseaseStatusTransitionModel;
import org.matsim.episim.model.testing.DefaultTestingModel;
import org.matsim.episim.model.testing.TestingModel;
import org.matsim.episim.model.vaccination.NoVaccination;
import org.matsim.episim.model.vaccination.VaccinationModel;
import org.matsim.episim.policy.FixedPolicy;
import org.matsim.episim.policy.ShutdownPolicy;
import org.matsim.vehicles.VehicleType;

import java.time.LocalDate;

/**
 * Runtime module for the Influenza Cologne scenario, run through the standard
 * {@code org.matsim.run.RunEpisim} runner:
 *
 * <pre>
 *   java -jar matsim-episim.jar --modules org.matsim.episim.run.modules.InfluenzaCologneScenario
 * </pre>
 *
 * <p>Simulates the 2025/26 influenza season on the Senozon Cologne population and its ordinary,
 * pre-pandemic activity pattern: no pandemic mobility reductions, no masks, no tracing. Almost
 * everything about the scenario &mdash; season dates, virus-strain and pathogen parameters including
 * the infectivity profile, the disease-import schedule, tracing, and disease-progression timing
 * (referenced from {@code Scenarios/Cologne/progression.conf}) &mdash; is plain data in
 * {@value #CONFIG_PATH}, loaded as-is. That file, and the cited source for every number in it, is
 * generated by {@link org.matsim.episim.run.scenarios.cologne.GenerateInfluenzaConfig} from
 * {@code docs/influenza-parameterisation.md}; re-run it after changing the scenario, edit the file
 * directly for anything smaller.</p>
 *
 * <p>The one exception is the contact-restriction <b>policy</b> ({@link #buildPolicy()}): the NRW
 * school holidays of 2025/26, in code. {@code EpisimConfigGroup.setPolicy}/{@code setProgressionConfig}
 * can only reference a file, never inline XML data, which is also why progression needed a sidecar
 * file rather than living directly in {@value #CONFIG_PATH}.</p>
 *
 * <p>This class also binds the Cologne-specific contact/infection models
 * ({@link SymmetricContactModel}, {@link AgeAndProgressionDependentInfectionModelWithSeasonality},
 * {@link AgeDependentDiseaseStatusTransitionModel}) that the parameterisation doc assumes &mdash;
 * Guice bindings, which cannot be expressed in a config file either. The COVID scenario's
 * {@code HouseholdSusceptibility} (35 % of households &times;5) is deliberately not bound: it is a
 * SARS-CoV-2 calibration without influenza evidence; keep it for a sensitivity run only.</p>
 *
 * <p><b>Known limitations</b> (see {@code docs/influenza-parameterisation.md} for detail): the
 * antibody / individual immunity model is still SARS-CoV-2 specific, so only influenza is seeded
 * (the SARS-CoV-2 disease import is cleared, so only one pathogen circulates), and the population
 * starts fully susceptible. Isolation at symptom onset is set to 75% home isolation, a
 * low-confidence value. The import follows the weekly NRW influenza notifications of 2025/26, but
 * its level is a calibration prior; the calibration target of {@code infectiousness} is still the
 * 2022/23 growth rate.</p>
 */
public final class InfluenzaCologneScenario extends AbstractModule {

	public static final String CONFIG_PATH = "Scenarios/Cologne/config.xml";

	/**
	 * Start of the simulated 2025/26 season: Monday of KW 39/2025, one week before the RKI influenza
	 * season, which runs from KW 40 to KW 20 (RKI, FAQ Grippesaison). Also set on
	 * {@code EpisimConfigGroup.startDate} in {@value #CONFIG_PATH}; duplicated here for the calendar
	 * below and the batch runner.
	 */
	public static final LocalDate SEASON_START = LocalDate.parse("2025-09-22");

	/** End of the simulated season: Sunday of KW 20/2026, the end of the RKI influenza season. */
	public static final LocalDate SEASON_END = LocalDate.parse("2026-05-17");

	/** School activities closed during NRW school holidays (kindergartens and universities stay open). */
	private static final String[] SCHOOLS = {"educ_primary", "educ_secondary", "educ_tertiary", "educ_other"};

	@Override
	protected void configure() {

		bind(ContactModel.class).to(SymmetricContactModel.class).in(Singleton.class);
		bind(InfectionModel.class).to(AgeAndProgressionDependentInfectionModelWithSeasonality.class).in(Singleton.class);
		bind(DiseaseStatusTransitionModel.class).to(AgeDependentDiseaseStatusTransitionModel.class).in(Singleton.class);
		bind(VaccinationModel.class).to(NoVaccination.class).in(Singleton.class);
		bind(TestingModel.class).to(DefaultTestingModel.class).in(Singleton.class);
		bind(ShutdownPolicy.class).to(FixedPolicy.class).in(Singleton.class);
		bind(ActivityParticipationModel.class).to(DefaultParticipationModel.class);

		// antibody model is SARS-CoV-2 specific and unused here (influenza induces no antibodies,
		// see docs/influenza-parameterisation.md), but EpisimModule requires an explicit binding
		AntibodyModel.Config antibodyConfig = new AntibodyModel.Config();
		antibodyConfig.setImmuneResponseSigma(3.0);
		bind(AntibodyModel.Config.class).toInstance(antibodyConfig);
	}

	@Provides
	@Singleton
	public Config config() {

		// episim's own groups must be registered up front: loadConfig only knows MATSim core groups and would
		// leave the rest raw, which MATSim's consistency check rejects as "unmaterialized"
		Config config = ConfigUtils.loadConfig(CONFIG_PATH,
				new EpisimConfigGroup(), new TracingConfigGroup(), new VirusStrainConfigGroup(), new PathogenConfigGroup());

		EpisimConfigGroup episimConfig = ConfigUtils.addOrGetModule(config, EpisimConfigGroup.class);
		episimConfig.setPolicy(buildPolicy().build());

		return config;
	}

	@Provides
	@Singleton
	public Scenario scenario(Config config) {

		config.vspExperimental().setVspDefaultsCheckingLevel(VspExperimentalConfigGroup.VspDefaultsCheckingLevel.warn);
		ControllerUtils.checkConfigConsistencyAndWriteToLog(config, "before loading scenario");

		final Scenario scenario = ScenarioUtils.loadScenario(config);

		configureVehicleCapacities(scenario, 1.3);

		return scenario;
	}

	/**
	 * Contact-restriction policy: everything open (the ordinary Senozon activity pattern), except
	 * schools during the NRW school holidays 2025/26. Activities without an entry stay at 1.0.
	 */
	public static FixedPolicy.ConfigBuilder buildPolicy() {

		FixedPolicy.ConfigBuilder policy = FixedPolicy.config();

		// NRW 2025/26, first and last day of each holiday (KMK, "Ferien im Schuljahr 2025/2026", Stand 09.10.2025):
		// Herbst 13.10.-25.10.2025, Weihnachten 22.12.2025-06.01.2026, Ostern 30.03.-11.04.2026. Pfingsten 26.05.2026
		// falls after SEASON_END. 0.2 is the residual fraction the COVID Cologne scenario used for closed schools,
		// kept as an assumption for holidays.
		closeSchools(policy, "2025-10-13", "2025-10-25");
		closeSchools(policy, "2025-12-22", "2026-01-06");
		closeSchools(policy, "2026-03-30", "2026-04-11");

		return policy;
	}

	private static void closeSchools(FixedPolicy.ConfigBuilder policy, String firstHoliday, String lastHoliday) {
		policy.restrict(LocalDate.parse(firstHoliday), 0.2, SCHOOLS);
		policy.restrict(LocalDate.parse(lastHoliday).plusDays(1), 1.0, SCHOOLS);
	}

	private static void configureVehicleCapacities(Scenario scenario, double capFactor) {
		for (VehicleType vehicleType : scenario.getVehicles().getVehicleTypes().values()) {
			switch (vehicleType.getId().toString()) {
				case "bus":
					vehicleType.getCapacity().setSeats((int) (70 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (40 * capFactor));
					break;
				case "metro":
					vehicleType.getCapacity().setSeats((int) (200 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (550 * capFactor));
					break;
				case "plane":
					vehicleType.getCapacity().setSeats((int) (200 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (0 * capFactor));
					break;
				case "pt":
					vehicleType.getCapacity().setSeats((int) (70 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (70 * capFactor));
					break;
				case "ship":
					vehicleType.getCapacity().setSeats((int) (150 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (150 * capFactor));
					break;
				case "train":
					vehicleType.getCapacity().setSeats((int) (250 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (750 * capFactor));
					break;
				case "tram":
					vehicleType.getCapacity().setSeats((int) (84 * capFactor));
					vehicleType.getCapacity().setStandingRoom((int) (216 * capFactor));
					break;
				default:
					throw new IllegalStateException("Unexpected value=|" + vehicleType.getId().toString() + "|");
			}
		}
	}

}
